Refactor code in main app
cherryshek-1014/react-projects pull request #1
Opened 2023-04-05 11:22 UTC by cherryshek-1014

2023-04-05 14:34 UTC, ColinCee requested changes

2023-04-05 14:34 UTC, ColinCee commented on pages/dictionary/search_history.tsx
> +    const searchWord = searchList.map((searchText, index) => {
Rename to searchedWords
```suggestion
    const searchedWords = searchList.map((searchText, index) => {
```

2023-04-05 14:34 UTC, ColinCee commented on pages/dictionary/search_history.tsx
> +    }
This seems redundant, you can just call setDisplayText in the below function

2023-04-05 14:34 UTC, ColinCee commented on pages/dictionary/search_history.tsx
> +                <button onClick={() => jumpTo(searchText)}>{searchText}</button>
```suggestion
                <button onClick={() => setDisplayText(searchText)}>{searchText}</button>
```

2023-04-12 11:37 UTC, cherryshek-1014 commented on pages/dictionary/search_history.tsx
> +    const searchWord = searchList.map((searchText, index) => {
Fixed in [[fd7af37](https://github.com/cherryshek-1014/react-projects/pull/1/commits/fd7af37fc7ed7b98e1e3bc3d55b96ac146b789b8)](url)

2023-04-12 11:37 UTC, cherryshek-1014 commented on pages/dictionary/search_history.tsx
> +    }
Fixed in [[fd7af37](https://github.com/cherryshek-1014/react-projects/pull/1/commits/fd7af37fc7ed7b98e1e3bc3d55b96ac146b789b8)](url)

2023-04-12 11:38 UTC, cherryshek-1014 commented on pages/dictionary/search_history.tsx
> +                <button onClick={() => jumpTo(searchText)}>{searchText}</button>
fixed in [[fd7af37](https://github.com/cherryshek-1014/react-projects/pull/1/commits/fd7af37fc7ed7b98e1e3bc3d55b96ac146b789b8)](url)

2023-04-12 17:02 UTC, ColinCee commented on pages/dictionary/index.tsx
>      const [searchList, setSearchList] = useState<string[]>([]);
Change this to searchedWords

2023-04-12 17:02 UTC, ColinCee commented on pages/dictionary/search_history.tsx
> +    const searchedWords = searchList.map((searchText, index) => {
Rename this to searchHistory

2023-04-12 17:02 UTC, ColinCee commented on pages/dictionary/index.tsx
> +            <History setDisplayText={setDisplayText} searchList={searchList} />
Remember to update references to searchedWords

2023-04-18 16:09 UTC, ColinCee approved these changes

2023-04-19 08:50 UTC, merged